name: test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --check-files
      - name: cache workspace
        uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn lint
    needs: [build]

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn test:unit
    needs: [build]

  test-fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn test:fixtures --passWithNoTests
    needs: [build]

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn test:e2e --passWithNoTests
    needs: [build]