name: test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10.x, 12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn lint
      - run: yarn test:unit
      - run: yarn test:fixtures --passWithNoTests
      - run: yarn test:e2e --passWithNoTests
